"""Phase 17B.2 - unified role permission templates.

These templates are the single source for default role access.
Admin can sync a user's role into UserFormPermission rows from the
Form Permissions screen. UserFormPermission rows remain the final
access control for a specific user after sync/customization.
"""

ACTIONS = ("view", "create", "edit", "delete", "approve", "print_export")


def perms(*actions):
    return {a: (a in actions) for a in ACTIONS}

FULL = perms(*ACTIONS)
VIEW = perms("view")
VIEW_PRINT = perms("view", "print_export")
VIEW_CREATE_EDIT = perms("view", "create", "edit")
VIEW_CREATE_EDIT_PRINT = perms("view", "create", "edit", "print_export")
VIEW_CREATE_EDIT_APPROVE_PRINT = perms("view", "create", "edit", "approve", "print_export")

ROLE_PERMISSION_DEFAULTS = {
    "Admin": "FULL_ACCESS",

    "Management": {
        "dashboard": VIEW,
        "projects": VIEW_PRINT,
        "project-tasks": VIEW_PRINT,
        "issues-risks": VIEW_PRINT,
        "documents": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "project-workforce": VIEW_PRINT,
        "forms-home": VIEW,
        "site-survey": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "load-assessment": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "daily-site-report": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "delivery-note": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "testing": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "commissioning": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "handover": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "materials": VIEW_PRINT,
        "material-items": VIEW_PRINT,
        "material-request": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "material-issue": VIEW_PRINT,
        "material-return": VIEW_PRINT,
        "material-reports": VIEW_PRINT,
        "sales-crm": VIEW_PRINT,
        "customer-inquiry": VIEW_CREATE_EDIT_PRINT,
        "quotation": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "quotation-items": VIEW_PRINT,
        "after-sales": VIEW_PRINT,
        "service-ticket": VIEW_CREATE_EDIT_PRINT,
        "warranty": VIEW_CREATE_EDIT_PRINT,
        "reports": VIEW_PRINT,
        "project-reports": VIEW_PRINT,
        "customer-reports": VIEW_PRINT,
        "form-reports": VIEW_PRINT,
        "customers": VIEW_CREATE_EDIT_PRINT,
        "employees": VIEW_PRINT,
        "teams": VIEW_PRINT,
        "notifications": VIEW_CREATE_EDIT_PRINT,
        "notification-log": VIEW_PRINT,
        "sms-queue": VIEW_PRINT,
        "whatsapp-integration": VIEW_PRINT,
        "production-readiness": VIEW_PRINT,
        "ai-assistant": VIEW_PRINT,
        "ai-crm-agent": VIEW_PRINT,
        "ai-project-manager": VIEW_PRINT,
        "ai-reports": VIEW_PRINT,
        "payroll": VIEW_PRINT,
    },

    "Operation Manager": {
        "dashboard": VIEW,
        "projects": VIEW_CREATE_EDIT_PRINT,
        "project-tasks": VIEW_CREATE_EDIT_PRINT,
        "issues-risks": VIEW_CREATE_EDIT_PRINT,
        "documents": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "project-workforce": VIEW_CREATE_EDIT_PRINT,
        "forms-home": VIEW,
        "site-survey": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "load-assessment": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "daily-site-report": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "delivery-note": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "testing": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "commissioning": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "handover": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "materials": VIEW_PRINT,
        "material-items": VIEW_PRINT,
        "material-request": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "material-issue": VIEW_CREATE_EDIT_PRINT,
        "material-return": VIEW_CREATE_EDIT_PRINT,
        "material-reports": VIEW_PRINT,
        "sales-crm": VIEW_PRINT,
        "customer-inquiry": VIEW_CREATE_EDIT_PRINT,
        "quotation": VIEW_CREATE_EDIT_APPROVE_PRINT,
        "quotation-items": VIEW_PRINT,
        "after-sales": VIEW_PRINT,
        "service-ticket": VIEW_CREATE_EDIT_PRINT,
        "warranty": VIEW_CREATE_EDIT_PRINT,
        "reports": VIEW_PRINT,
        "project-reports": VIEW_PRINT,
        "customer-reports": VIEW_PRINT,
        "form-reports": VIEW_PRINT,
        "customers": VIEW_CREATE_EDIT_PRINT,
        "employees": VIEW_PRINT,
        "teams": VIEW_CREATE_EDIT_PRINT,
        "notifications": VIEW_CREATE_EDIT_PRINT,
        "notification-log": VIEW_PRINT,
        "whatsapp-integration": VIEW_PRINT,
        "production-readiness": VIEW_PRINT,
        "ai-assistant": VIEW_PRINT,
        "ai-project-manager": VIEW_PRINT,
    },

    "Technical Engineer": {
        "dashboard": VIEW,
        "projects": VIEW_PRINT,
        "project-tasks": VIEW_CREATE_EDIT_PRINT,
        "issues-risks": VIEW_CREATE_EDIT_PRINT,
        "documents": VIEW_CREATE_EDIT_PRINT,
        "project-workforce": VIEW_PRINT,
        "forms-home": VIEW,
        "site-survey": VIEW_CREATE_EDIT_PRINT,
        "load-assessment": VIEW_CREATE_EDIT_PRINT,
        "daily-site-report": VIEW_CREATE_EDIT_PRINT,
        "testing": VIEW_CREATE_EDIT_PRINT,
        "commissioning": VIEW_CREATE_EDIT_PRINT,
        "handover": VIEW_CREATE_EDIT_PRINT,
        "material-request": VIEW_CREATE_EDIT_PRINT,
        "material-reports": VIEW_PRINT,
        "after-sales": VIEW,
        "service-ticket": VIEW_CREATE_EDIT_PRINT,
        "warranty": VIEW_PRINT,
        "reports": VIEW_PRINT,
        "project-reports": VIEW_PRINT,
        "form-reports": VIEW_PRINT,
        "customers": VIEW,
        "ai-assistant": VIEW_PRINT,
        "ai-project-manager": VIEW_PRINT,
    },

    "Site Supervisor": {
        "dashboard": VIEW,
        "projects": VIEW_PRINT,
        "project-tasks": VIEW_CREATE_EDIT_PRINT,
        "issues-risks": VIEW_CREATE_EDIT_PRINT,
        "documents": VIEW_CREATE_EDIT_PRINT,
        "forms-home": VIEW,
        "site-survey": VIEW_CREATE_EDIT_PRINT,
        "daily-site-report": VIEW_CREATE_EDIT_PRINT,
        "delivery-note": VIEW_CREATE_EDIT_PRINT,
        "testing": VIEW_CREATE_EDIT_PRINT,
        "commissioning": VIEW_CREATE_EDIT_PRINT,
        "handover": VIEW_CREATE_EDIT_PRINT,
        "material-request": VIEW_CREATE_EDIT_PRINT,
        "service-ticket": VIEW_CREATE_EDIT_PRINT,
        "warranty": VIEW,
        "project-reports": VIEW_PRINT,
        "form-reports": VIEW_PRINT,
        "customers": VIEW,
        "ai-assistant": VIEW_PRINT,
    },

    "Warehouse Officer": {
        "dashboard": VIEW,
        "projects": VIEW,
        "documents": VIEW_CREATE_EDIT_PRINT,
        "forms-home": VIEW,
        "delivery-note": VIEW_CREATE_EDIT_PRINT,
        "materials": VIEW_PRINT,
        "material-items": VIEW_CREATE_EDIT_PRINT,
        "material-request": VIEW_CREATE_EDIT_PRINT,
        "material-issue": VIEW_CREATE_EDIT_PRINT,
        "material-return": VIEW_CREATE_EDIT_PRINT,
        "material-reports": VIEW_PRINT,
        "customers": VIEW,
        "reports": VIEW_PRINT,
    },

    "Transport Officer": {
        "dashboard": VIEW,
        "projects": VIEW,
        "documents": VIEW_CREATE_EDIT_PRINT,
        "forms-home": VIEW,
        "delivery-note": VIEW_CREATE_EDIT_PRINT,
        "material-request": VIEW,
        "material-issue": VIEW,
        "customers": VIEW,
    },

    "Sales Officer": {
        "dashboard": VIEW,
        "customers": VIEW_CREATE_EDIT_PRINT,
        "sales-crm": VIEW_PRINT,
        "customer-inquiry": VIEW_CREATE_EDIT_PRINT,
        "quotation": VIEW_CREATE_EDIT_PRINT,
        "quotation-items": VIEW_CREATE_EDIT_PRINT,
        "whatsapp-integration": VIEW_CREATE_EDIT_PRINT,
        "projects": VIEW_PRINT,
        "forms-home": VIEW,
        "load-assessment": VIEW_CREATE_EDIT_PRINT,
        "after-sales": VIEW,
        "service-ticket": VIEW_CREATE_EDIT_PRINT,
        "warranty": VIEW_CREATE_EDIT_PRINT,
        "customer-reports": VIEW_PRINT,
        "ai-assistant": VIEW_PRINT,
        "ai-crm-agent": VIEW_PRINT,
    },

    "Finance Officer": {
        "dashboard": VIEW,
        "customers": VIEW_PRINT,
        "projects": VIEW_PRINT,
        "sales-crm": VIEW_PRINT,
        "quotation": VIEW_PRINT,
        "reports": VIEW_PRINT,
        "project-reports": VIEW_PRINT,
        "customer-reports": VIEW_PRINT,
        "form-reports": VIEW_PRINT,
        "payroll": VIEW_PRINT,
        "documents": VIEW_CREATE_EDIT_PRINT,
        "material-reports": VIEW_PRINT,
    },
}

ROLE_PERMISSION_SUMMARY = {
    "Admin": ["Full system access", "No manual permission rows required"],
    "Management": ["Management dashboards/reports", "Approvals", "View and print most modules"],
    "Operation Manager": ["Projects, forms, operations", "Approvals", "Sales/project coordination"],
    "Technical Engineer": ["Project forms", "Technical documents", "Project reports"],
    "Site Supervisor": ["Site forms", "Daily reports", "Testing and handover"],
    "Warehouse Officer": ["Materials", "Stock movement", "Delivery notes"],
    "Transport Officer": ["Delivery notes", "Transport-related project access"],
    "Sales Officer": ["Customers", "Leads", "Quotations", "WhatsApp CRM"],
    "Finance Officer": ["Reports", "Documents", "Finance-related views"],
}
